add_executable(shipglows_audio_engine_tests
  engine_tests.cpp
)

target_compile_features(shipglows_audio_engine_tests PRIVATE cxx_std_20)
target_link_libraries(shipglows_audio_engine_tests PRIVATE shipglows::audio_engine)

add_test(NAME shipglows_audio_engine_tests COMMAND shipglows_audio_engine_tests)
